### ISSUE TITLE
Cal State Serverless IIIF & S3

### ISSUE THREAD

**Issue by aprilrieger** [scientist-softserv/scholarworks#25]
SOW: https://docs.google.com/document/d/1hVD2QW2tvyR0r9YpqEw7kTYNydmCiFYkxX5wRDBYBwI/edit

Outline of Work:
- [x] April: Log into cal state AWS account
     - create s3 bucket
     - create Serverless IIIF lambda [link](https://samvera.github.io/serverless-iiif/)
- [x] Kiah: Update the code
    - someone with code access pairing with Shana to do the code change to have a serverless set and getting it deployed (Kiah & Shana)
- [x] Rob: #26 
- [x] [Add `SERVERLESS_IIIF_URL` ENV variable to prod](https://assaydepot.slack.com/archives/C030UPFCDSS/p1717101138972219?thread_ts=1717098910.587699&cid=C030UPFCDSS) 

`SERVERLESS_IIIF_URL=https://6cff3iwnwia62qiqak74dkfsku0fwjsd.lambda-url.us-west-2.on.aws/iiif/2`

on `digital_archives_hyrax_0`
Apache configuration at `/etc/httpd/vhost.d/archives.calstate.edu.conf`

on hyrax_0 & hyrax_1
Apache configuration at `/etc/httpd/vhost.d/scholarworks.conf`

`sudo systemctl restart httpd`

- [x] ~~Reindex all file sets (and works?)~~ Not necessary (see [this thread](https://assaydepot.slack.com/archives/C0313NK5NMA/p1717186053795009))

**Comment by aprilrieger** [comment]
Bucket:
region: `us-west-2`
name: `hyrax-fcrepo-cache`
AWS direct [link](https://us-west-2.console.aws.amazon.com/s3/buckets/hyrax-fcrepo-cache?region=us-west-2&bucketType=general&tab=objects) once logged in under csu role

Lambda Function:
region: `us-west-2`
function url: `https://6cff3iwnwia62qiqak74dkfsku0fwjsd.lambda-url.us-west-2.on.aws/`
AWS direct [link](https://us-west-2.console.aws.amazon.com/lambda/home?region=us-west-2#/functions) once logged in under csu role

**Comment by ShanaLMoore** [comment]
This comment may be useful: https://docs.google.com/document/d/1hVD2QW2tvyR0r9YpqEw7kTYNydmCiFYkxX5wRDBYBwI/edit?disco=AAABNlusXuQ

**Comment by bkiahstroud** [comment]
[The PR with the code update](https://dev.azure.com/csu-co/Systemwide%20Digital%20Library%20Services/_git/ScholarWorks/pullrequest/303) was merged on Aug 8

**Comment by aprilrieger** [comment]
I added the env variable to production 
hyrax_0 and hyrax_1 added env var to:
/etc/httpd/vhost.d/scholarworks.conf
`SetEnv SERVERLESS_IIIF_URL https://hyrax-fcrepo-cache.s3.us-west-2.amazonaws.com`

and added in the worker /var/www/hyrax/.env 
`SERVERLESS_IIIF_URL=https://hyrax-fcrepo-cache.s3.us-west-2.amazonaws.com`
`SERVERLESS_IIIF_URL=https://hyrax-fcrepo-cache.s3.us-west-2.amazonaws.com/iiif/2`

Wehn testing to see if the iiif objs are available form the manifest `https://6cff3iwnwia62qiqak74dkfsku0fwjsd.lambda-url.us-west-2.on.aws/iiif/2/86cd80b40ff6eaa062339ab82655dcfa/full/600,/0/default.jpg` When navigating to image from manifest I was given a not found error.

**Comment by aprilrieger** [comment]
New PR up for client to review and deploy to production so we can add the env var and restart the server for the changes to take effect. https://dev.azure.com/csu-co/Systemwide%20Digital%20Library%20Services/_git/ScholarWorks/pullrequest/305
