### ISSUE TITLE
Site24x7 agent process

### ISSUE THREAD

**Issue by jillpe** [scientist-softserv/scholarworks#27]
## Summary
https://assaydepot.slack.com/archives/C030UPFCDSS/p1717781622402639
David: "I just rebooted the Digital Archives Hyrax instance, since it was seized up.  It doesn't look like there is a Site24x7Agent process running on that server,  prod-da-hyrax, or the corresponding worker server for the Digital Archives, prod-da-worker.  At your earliest convenience, can someone get that set up?"

## Acceptance Criteria
- [x] Site24x7Agent process is set up on `prod-da-hyrax` or `prod-da-worker`

**Comment by bkiahstroud** [comment]
I configured the server monitors and confirmed that email, Slack, and PagerDuty integrations are working
